### ISSUE TITLE
[BUG] Argo - Segmentation error

### ISSUE THREAD

**Issue by Nihit13** [thecoder-001/MineColab#58] opened 2021-11-03 02:14 UTC
**Describe the bug*
I was surfing on internet when I came across this project..... Felt pretty interesting so tried using it...... the argo tunnel doen't work ... it gives an error saying that 

ERR Failed to create new quic connection, err: Unauthorized: Record for tunnel not found
ERR Register tunnel error from server side error="Unauthorized: Record for tunnel not found" connIndex=0

Unhandled exception
Type=Segmentation error vmState=0x00000000

**To Reproduce**
This error occurred when it was set as default to 'argo'

**Expected behavior**
I was expecting to get the tunnel address so that I can connect to the server 

**Screenshots**

**Minecraft server Version**
The Minecraft version is 1.17.1

**Mod/Datapack list**
There are no mods currently running on the server

**Additional context**

**Comment by thecoder-001** [comment] 2022-05-29 22:05
Hello!
Apologies for the late reply, the tunnel seems to be working for me in my testings. Maybe give it another go?
Closing the issue for now, please reopen if the issue is still there.

**Closed by thecoder-001** 2022-05-29 22:05 UTC
Labels: bug
