### ISSUE TITLE
[BUG] Ngrok connection problems

### ISSUE THREAD

**Issue by sudo216** [thecoder-001/MineColab#24] opened 2021-01-29 04:43 UTC
**Describe the bug**
its now not letting to connect,it starts but we can't able to join it .
it says is it a minecraft server?
i guess minecraft server has got banned on google colab now :(

**Expected behavior**
it should let us in.

**Comment by YOYITsM3M8** [comment] 2021-01-29 12:48
What IP are you using

**Comment by TinoMartino094** [comment] 2021-01-29 14:08
I'm having the same issue using 4.tcp.ngrok.io:10196 IP and it show's this error
![error](https://user-images.githubusercontent.com/78217336/106284691-85948000-6211-11eb-841f-1ae1e5b85a9f.png)

**Comment by YOYITsM3M8** [comment] 2021-01-29 14:48
what server version?

**Comment by TinoMartino094** [comment] 2021-01-29 15:09
1.16.5

**Comment by YOYITsM3M8** [comment] 2021-01-29 17:08
What version of client

**Comment by TinoMartino094** [comment] 2021-01-29 17:40
Both of them 1.16.4 and 1.16.5 Its not a mc issue as far as I can tell, Is prob a ngrok issue

**Comment by orangemn6** [comment] 2021-01-29 18:06
This comment blew up on discord btw

**Comment by orangemn6** [comment] 2021-01-29 18:07
also https://dontasktoask.com

**Comment by TinoMartino094** [comment] 2021-01-29 18:40
> This comment blew up on discord btw

@orangemn6 what discord?
 lol

**Comment by Tokaroi** [comment] 2021-01-29 20:00
@orangemn6  what discord?

**Comment by venkyMacha** [comment] 2021-01-29 20:11
> This comment blew up on discord btw

What discord?

**Comment by Tokaroi** [comment] 2021-01-29 20:13
> > This comment blew up on discord btw
> 
> What discord?

hi lol

**Comment by Faroutiner** [comment] 2021-01-29 20:23
I have the same problem, is it possible that Google is blocking connections?
![32312](https://user-images.githubusercontent.com/58443512/106323774-40efff80-6278-11eb-9f54-8041d97fceef.jpeg)

**Comment by venkyMacha** [comment] 2021-01-30 04:17
> > > This comment blew up on discord btw
> > 
> > 
> > What discord?
> 
> hi

Hello!

**Comment by yougeshlama** [comment] 2021-01-30 10:56
Sed missing google colab :(

**Comment by Snavellet** [comment] 2021-01-30 12:54
Bruh

**Comment by Benjimanrich** [comment] 2021-01-30 13:47
wtf is happening

**Comment by thecoder-001** [comment] 2021-01-30 15:28
Hello everyone!
Don't worry, the issue is currently being looked under. Preliminary testing shows that it seems to be a fault of ngrok and not google colab itself. Further investigation is still needed to sort things out, but you all are requested to try to connect using a fresh ngrok account  (as it can be a  recurrence of issue #8 ) and try a vpn once till then.
Comments were deleted to keep things more on-topic. For casual conversation, you all requested to go to <a href="https://github.com/thecoder-001/MineColab/discussions">discussions</a> in the future.

Cheers

**Comment by Faroutiner** [comment] 2021-01-30 22:00
Checked with another ngrok account, still doesn't work

**Comment by Genvara** [comment] 2021-01-31 09:38
Same thing, it doesn't work

(psst you can use lynk.sh meanwhile)

**Comment by Faroutiner** [comment] 2021-01-31 11:32
Thanks! lynk.sh works fine!
Documentation was really useful (https://lynk.sh/docs?p=0)

> Same thing, it doesn't work
> 
> (psst you can use lynk.sh meanwhile)

**Comment by Faroutiner** [comment] 2021-01-31 13:18
I thought it would be a good idea to write a step-by-step guide on how to run lynk.sh

**This steps you will need to do only once:**
1. Go to [lynk.sh](https://lynk.sh/ )
2. Create an account 
3. Go to [lynk documentation]( https://lynk.sh/docs?p=2) and download lynk.zip for linux
![image](https://user-images.githubusercontent.com/58443512/106382839-71dc4b80-63c2-11eb-8f1b-01d57d58f77b.png)

4. Once you have downloaded it, unzip it by a program of your choice (for example WinRar <3)
5. Upload unzipped lynk file to your Google Drive (to the main folder or create a new one)
6. You should create a new cell in your colab notepad and paste this code:
```
!pip install kora > /dev/null 2>&1 || echo "Failed to install kora (console thing) :("
from kora import console

from google.colab import drive
drive.mount('/content/drive')

LYNK_TOKEN = "YOUR_TOKEN"
LYNK_KEY = "YOUR_KEY"

commands = open('get_ip', 'w')
commands.write(f"cd '/content/drive/My Drive/PATH_TO_LYNK_FILE' && chmod +x lynk && ./lynk auth -t {LYNK_TOKEN} -k {LYNK_KEY} && ./lynk tcp 25565")
commands.close()
!chmod +x get_ip

print("Link to console:")
console.start()
```
**Note**: instead of PATH_TO_LYNK_FILE write your path to lynk file which you have uploaded earlier, for example, if you uploaded it to main folder this line should look like this: `! cd /content/drive/MyDrive`, if you created a folder named "Lynk" this line of code should look like this:  `! cd /content/drive/MyDrive/Lynk` etc.
**Another Note**: Instead of YOUR_TOKEN and YOUR_KEY, you should paste your own token and key and you can get it from [here](https://lynk.sh/dashboard) by clicking "Generate Lynk Token":
![image](https://user-images.githubusercontent.com/58443512/106383385-e2389c00-63c5-11eb-9e37-e2b4d4084d94.png)

7. (**You will need to repeat this step every time before starting server**) Now run cell you've created in step 6, 
and go to the Console URL,
![image](https://user-images.githubusercontent.com/58443512/106384721-976e5280-63cc-11eb-9f8b-c3b293d4a28d.png)
write `./get_ip` and click enter
![image](https://user-images.githubusercontent.com/58443512/106384742-b8cf3e80-63cc-11eb-94a1-a133e161af7a.png)
And here is your IP:
![image](https://user-images.githubusercontent.com/58443512/106385010-48c1b800-63ce-11eb-8523-b15c7af6f9b4.png)
Now you can close this window and run the server.
I hope I've helped, if you have any questions, or instruction seem unclear, tag me.

PS I know there is probably a better way to do it.

**Comment by yougeshlama** [comment] 2021-01-31 17:22
guys u can also use playit.gg for tcp tunneling

**Comment by TinoMartino094** [comment] 2021-01-31 17:41
> guys u can also use playit.gg for tcp tunneling

Do u know how to use it on a ubuntu console environment?
I was checking how to do it but I wasn't able to find a way

**Comment by ShivanshVij** [comment] 2021-01-31 23:47
Hey guys, creator of Lynk here, ping me if you need any help or have any questions!

**Comment by TinoMartino094** [comment] 2021-02-01 03:23
Do you know if there is any way to have the tunnel on a phyton API like pyngrok, so we can run it on the background and have the IP as a variable?

**Comment by Genvara** [comment] 2021-02-01 10:02
> guys u can also use playit.gg for tcp tunneling

iam aware of it, however how does it work in a terminal

**Comment by yougeshlama** [comment] 2021-02-02 14:07
same as the lynk just change some value :) although sorry for late reply

>

**Comment by Merendino1234** [comment] 2021-02-03 07:38
only for me the server is working fine?
I now discovered that u can change the hosting region (us,eu)
and this reduced my ping to 20 amazing

**Comment by yougeshlama** [comment] 2021-02-06 10:31
yeh you can change the region :) to in,eu.us

**Closed** 2021-07-23 05:49 UTC
Labels: bug

**Comment by turtleship69** [comment] 2022-10-01 11:19
> 

I can try to make a pr to add this as a default option?

**Comment by turtleship69** [comment] 2022-10-01 11:20
> I thought it would be a good idea to write a step-by-step guide on how to run lynk.sh
> 
> **This steps you will need to do only once:**
> 
> 1. Go to [lynk.sh](https://lynk.sh/)
> 2. Create an account
> 3. Go to [lynk documentation](https://lynk.sh/docs?p=2) and download lynk.zip for linux
>    ![image](https://user-images.githubusercontent.com/58443512/106382839-71dc4b80-63c2-11eb-8f1b-01d57d58f77b.png)
> 4. Once you have downloaded it, unzip it by a program of your choice (for example WinRar <3)
> 5. Upload unzipped lynk file to your Google Drive (to the main folder or create a new one)
> 6. You should create a new cell in your colab notepad and paste this code:
> 
> ```
> !pip install kora > /dev/null 2>&1 || echo "Failed to install kora (console thing) :("
> from kora import console
> 
> from google.colab import drive
> drive.mount('/content/drive')
> 
> LYNK_TOKEN = "YOUR_TOKEN"
> LYNK_KEY = "YOUR_KEY"
> 
> commands = open('get_ip', 'w')
> commands.write(f"cd '/content/drive/My Drive/PATH_TO_LYNK_FILE' && chmod +x lynk && ./lynk auth -t {LYNK_TOKEN} -k {LYNK_KEY} && ./lynk tcp 25565")
> commands.close()
> !chmod +x get_ip
> 
> print("Link to console:")
> console.start()
> ```
> 
> **Note**: instead of PATH_TO_LYNK_FILE write your path to lynk file which you have uploaded earlier, for example, if you uploaded it to main folder this line should look like this: `! cd /content/drive/MyDrive`, if you created a folder named "Lynk" this line of code should look like this: `! cd /content/drive/MyDrive/Lynk` etc.
> 
> **Another Note**: Instead of YOUR_TOKEN and YOUR_KEY, you should paste your own token and key and you can get it from [here](https://lynk.sh/dashboard) by clicking "Generate Lynk Token": ![image](https://user-images.githubusercontent.com/58443512/106383385-e2389c00-63c5-11eb-9e37-e2b4d4084d94.png)
> 
> 7. (**You will need to repeat this step every time before starting server**) Now run cell you've created in step 6,
>    and go to the Console URL,
>    ![image](https://user-images.githubusercontent.com/58443512/106384721-976e5280-63cc-11eb-9f8b-c3b293d4a28d.png)
>    write `./get_ip` and click enter
>    ![image](https://user-images.githubusercontent.com/58443512/106384742-b8cf3e80-63cc-11eb-94a1-a133e161af7a.png)
>    And here is your IP:
>    ![image](https://user-images.githubusercontent.com/58443512/106385010-48c1b800-63ce-11eb-8523-b15c7af6f9b4.png)
>    Now you can close this window and run the server.
> 
> I hope I've helped, if you have any questions, or instruction seem unclear, tag me. PS I know there is probably a better way to do it.
> 
> Love, Farout


I can try to make a pr to add this as a default option?

(ignore my deleted comment, quote reply failed)

**Comment by thecoder-001** [comment] 2022-10-01 18:17
Hi!
Unfortunately [lynk.sh](https://lynk.sh) seems to have been shut down. The website too seems to open for me.
Digging around a bit, it seems to be connected to loopholelabs, though they don't seem to offer any services similar to lynk. 

There's even a [issue](https://github.com/anderspitman/awesome-tunneling/issues/23) on Github discussing what happend to lynk, indicating that would be re-released though I don't think that would happen (considering how old the message is).
